name: Backend CI/CD Deployment

on:
  push:
    branches:
      - master  # Backend deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: false  # Explicitly disable submodules to avoid errors

      # ---- BACKEND DEPLOYMENT ----
      - name: Deploy Backend
        if: github.ref == 'refs/heads/master'
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST_GEN }}
          username: ${{ secrets.SERVER_USER_GEN }}
          key: ${{ secrets.SSH_PRIVATE_KEY_GEN }}
          script: |
            # Display current directory and hidden files
            ls -a
            pwd

            # Navigate to the backend application folder
            cd /home/ubuntu/backend/Generative_ai

            # Clean up any submodule references (just in case)
            git submodule deinit -f --all || true
            rm -rf .git/modules || true
            git config --global --unset-all safe.directory || true

            # Stash any local changes and pull the latest code
            sudo git stash
            git checkout master
            sudo git pull origin master

            # Install dependencies using the virtual environment's pip
            /home/ubuntu/backend/venv/bin/pip install -r requirements.txt

            # Restart the application service
            sudo systemctl restart uvicorn.service
